id: data_ingestion_2019_2020_csv
namespace: zoomcamp

inputs:
- id: taxi
  type: SELECT
  displayName: Select taxi type
  values: [ 'yellow', green ]
  defaults: yellow

variables:
  file: "{{inputs.taxi}}_tripdata_{{trigger.date | date('yyyy-MM')}}.csv"
  gcs_file: "gs://{{kv('GCP_BUCKET_NAME')}}/{{vars.file}}"
  data: "{{outputs.extract.outputFiles[inputs.taxi ~ '_tripdata_' ~ (trigger.date | date('yyyy-MM')) ~ '.csv']}}"

tasks:
- id: set_label
  type: io.kestra.plugin.core.execution.Labels
  labels:
    file: "{{render(vars.file)}}"
    taxi: "{{inputs.taxi}}"

- id: extract
  type: io.kestra.plugin.scripts.shell.Commands
  outputFiles:
  - "*.csv"
  taskRunner:
    type: io.kestra.plugin.core.runner.Process
  commands:
  - wget -qO- https://github.com/DataTalksClub/nyc-tlc-data/releases/download/{{inputs.taxi}}/{{render(vars.file)}}.gz | gunzip > {{render(vars.file)}}

- id: upload_to_gcs
  type: io.kestra.plugin.gcp.gcs.Upload
  from: "{{render(vars.data)}}"
  to: "{{render(vars.gcs_file)}}"

- id: purge_files
  type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
  description: Remove the donwloaded files

pluginDefaults:
- type: io.kestra.plugin.gcp
  values:
    serviceAccount: "{{kv('GCP_CREDS')}}"
    projectId: "{{kv('GCP_PROJECT_ID')}}"
    location: "{{kv('GCP_LOCATION')}}"
    bucket: "{{kv('GCP_BUCKET_NAME')}}"

triggers:
- id: yellow_trigger
  type: io.kestra.plugin.core.trigger.Schedule
  cron: "0 9 1 * *"
  inputs:
    taxi: yellow
